eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/

server:
  port: 8104

spring:
  application:
    name: service-a-4